### ISSUE TITLE
Wallabag v2 support?

### ISSUE THREAD

**Issue by celebrion** [wallabag/ios-app-v1#38]
Will the iOS app support Wallabag v2 installations soon?

**Comment by frootmig** [comment]
I have the same problem. App does not work after upgrading to v2.

**Comment by 0wnrepo** [comment]
I'll look into this in the following weekend.

**Comment by vasbinde** [comment]
It's sad, but I think this app is dead.  no development for over a year.

**Comment by frootmig** [comment]
At least 0wnrepo commented 18 days ago on this issue. So there is still hope that there might be an update for v2.

**Comment by devianer** [comment]
Would still be interested in helping out with development...

Am 26.07.2016 um 17:58 schrieb Volker Janzen <notifications@github.com<mailto:notifications@github.com>>:


At least 0wnrepo commented 18 days ago on this issue. So there is still hope that there might be an update for v2.

**Comment by celebrion** [comment]
Any progress on this? With the release of Wallabag 2.1 an updated iOS app would be awesome!

**Comment by devianer** [comment]
I would love to help out. Who is working on it atm?

**Comment by nicosomb** [comment]
Nobody.

**Comment by devianer** [comment]
That's okay. I will try to have a look at it.

**Comment by nicosomb** [comment]
FYI https://twitter.com/bourvill/status/798231305888534528

**Comment by j0k3r** [comment]
:arrow_right: https://github.com/wallabag/ios-app
